---

- name: Ensure software-properties-common is installed
  ansible.builtin.apt:
    name: software-properties-common

- name: Ensure python is installed
  ansible.builtin.apt:
    name: python3

- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip

- name: Ensure Python library docker
  ansible.builtin.pip:
    name: docker

- name: Ensure Python library docker-compose
  ansible.builtin.pip:
    name: docker-compose

- name: Ensure authentik base directory
  ansible.builtin.file:
    path:  "{{ authentik_base_directory }}"
    state: directory
    mode:  '0700'

- name: Ensure authentik .env file
  ansible.builtin.template:
    src:   .env.j2
    dest:  "{{ authentik_base_directory }}/.env"
    force: true
    mode: '0770'

- name: Ensure authentik docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ authentik_base_directory }}/docker-compose.yml"
    force: true
    mode: '0770'

- name: Ensure authentik is installed with docker-compose
  community.docker.docker_compose:
    project_src: "{{ authentik_base_directory }}"
    state: present

- name: Ensure mailcow is running with docker compose command
  ansible.builtin.command:
    cmd:   "docker compose up --detach"
    chdir: "{{ authentik_base_directory }}"

...